### ISSUE TITLE
Examples with momoize from readme don't work

### ISSUE THREAD

**Issue by solnic** [dkubb/adamantium#11]
I'm getting this when trying to use `momoize :method_name`:

```
/Users/solnic/.rvm/gems/ruby-1.9.3-p327@virtus/gems/adamantium-0.0.5/lib/adamantium.rb:93:in `memoize': wrong number of arguments (1 for 2) (ArgumentError)
```

When I try using :freezer option I'm getting this:

```
/Users/solnic/.rvm/gems/ruby-1.9.3-p327@virtus/gems/adamantium-0.0.5/lib/adamantium.rb:142:in `freezer': undefined method `freezer' for Class:Class (NoMethodError)
```

I guess you need to add specs using code from examples otherwise it's gonna be hard to keep readme up-to-date.

**Comment by mbj** [comment]
The examples should work perfectly. There was no disruptive API change since the examples where written. We only added the `:freezer` option. Can you show more code?

**Comment by mbj** [comment]
This was resolved in channel. Adamantium was used with `extend Adamantium` not `include Adamantium`. Closing issue.
