### ISSUE TITLE
new! method

### ISSUE THREAD

**Issue by misfo** [dkubb/adamantium#19]
I think it's a good idea that by default instance variables are `dup`ed before they're frozen, since there's no way to know inside of adamantium whether or not the user is referencing the object elsewhere where it can't be frozen. But it leads to this idiom:

``` ruby
hash = JSON.parse json
IceNine.deep_freeze hash
SomeAdamantiumClass.new hash
```

The second line is there purely to prevent `hash` from being `dup`ed. In cases like this know `hash` can be frozen without `dup`ing because we "own" the only reference to it.

My question: would it make sense for adamantium to have a `new!` method that skipped the `dup`ing? It would potentially freeze some of the objects passed into it, but it would make the above code into this:

``` ruby
hash = JSON.parse json
SomeAdamantiumClass.new! hash
```

**Comment by mbj** [comment]
Nice idea. I support this.

**Comment by dkubb** [comment]
I would support this too.

**Comment by misfo** [comment]
For my particular use case [`IceNine.deep_freeze!`](https://github.com/dkubb/ice_nine/blob/master/lib/ice_nine.rb#L58) is what I want anyways. (when it's released ;) ) It'd be weird if there were two variations of `new!` in order to specify whether you want use `deep_freeze` or `deep_freeze!`.

I'm thinking I'll start using the core extensions for this gem, so this seems to be expressive enough:

``` ruby
hash = JSON.parse json
SomeAdamantiumClass.new hash.deep_freeze!
```
