### ISSUE TITLE
Release version 0.2.0

### ISSUE THREAD

**Issue by sferik** [dkubb/adamantium#28]
A [bunch of things have changed](https://github.com/dkubb/adamantium/compare/0077c03aa3e0331b6cda729b54c024f59d150378...master) since version 0.1.0 was released in August. Most notably, memoization is now an external dependency instead of a built-in feature. This means `memoizable` version 0.4.0 and `adamantium` version 0.1.0 are incompatible. Projects that would like to use both projects must choose one or the other. Releasing a new gem version of this library will fix this problem.

I’d recommend merging this [pull request to update the `memoizable` dependency](https://github.com/dkubb/adamantium/pull/26) before shipping the next version.

**Comment by dkubb** [comment]
I have released 0.2.0 with the updated memoizable dependency.

**Comment by sferik** [comment]
Thanks!
