### ISSUE TITLE
Name clash with immutable gem by shugo

### ISSUE THREAD

**Issue by zaidan** [dkubb/adamantium#3]
Please fix name clash with immutable gem by shugo:
http://rubygems.org/gems/immutable

**Comment by mbj** [comment]
@dkubb I realized the name clash confuses also gemnasium dependency tracking. Lets choose something else.

**Comment by solnic** [comment]
How about immutant? :)

**Comment by mbj** [comment]
Yeah! mutant vs immutant. Ready. Fight!

@dkubb Lets pick this! (Rename repo if you agree).

**Comment by misfo** [comment]
Immutant is a Red Hat trademark:
http://immutant.org/

**Comment by misfo** [comment]
What about something to do with values? "Valued", "Valuable", etc...

**Comment by mbj** [comment]
I do not think we'll go into problems when we are naming a small support gem the same as a trademarked application server.

Virtus is also [taken](http://www.virtus.org) outside the ruby world. And I'd bet I can find more examples quite easily.

**Comment by dkubb** [comment]
What about adamantium? ;)

**Comment by solnic** [comment]
@dkubb that would be epic :D

**Comment by mbj** [comment]
Imho this does not read well.

``` ruby
class FooBar
  include Admantium
end
```

But `include Immutable` does directly communicate what it does.

**Comment by solnic** [comment]
Come on. Everybody knows what Admantium is and will immediately know what it does ;)

**Comment by zaidan** [comment]
I did not ;)

What about Immutanium or Immutan?
Am 11.10.2012 12:09 schrieb "Piotr Solnica" notifications@github.com:

**Comment by mbj** [comment]
Lets bring back discussion to the very nice suggestion ``immutant`. I do not really see copyright/trademark problems. Can someone enlight me?

**Comment by dkubb** [comment]
@mbj I don't want there to be any confusion with your awesome gem mutant. I realize it's not even in the same category, but we likely will be talking about the tools we use in the same breath as the main DataMapper gems, and support gems like this one. I don't want there to be any confusion for people thinking "mutant" and "immutant" are related in anyway.

@solnic I think I am going to go with adamantium for the name. I realize there's a part of the population that does not know anything about comic books, but I think it's wide spread enough that it's not a complete mystery.

I'll rename the gem and register the name today.

**Comment by mbj** [comment]
@dkubb Thx for just picking one.

**Comment by dkubb** [comment]
This gem name has been changed from immutable to adamantium.

Also I released 0.0.1 on rubygems to reserve the gem name.

**Comment by solnic** [comment]
@dkubb awesome. I'm going to start using it in dm-mapper, dm-session and virtus soon.

**Comment by mbj** [comment]
@solnic dm-session is using immutable already since it was born.
