### ISSUE TITLE
MRI 2.1.0-p0 segfault

### ISSUE THREAD

**Issue by ghost** [dkubb/adamantium#30]
Occurs in [Adamantium::ClassMethods#new](https://github.com/dkubb/adamantium/blob/master/lib/adamantium/class_methods.rb#L17)
Core dump: https://gist.github.com/lgierth/8411173

Getting this with both 0.1.0 and current master (7076723698b1).

I'm figuring out whether this has already been reported to MRI, there are a couple of recent segfault-related tickets, but they seem unrelated to this one.

**Comment by ghost** [comment]
On Travis as well: https://travis-ci.org/lgierth/promise.rb/jobs/16904962

**Comment by ghost** [comment]
Ah, it's fixed in 2.2.0dev (2014-01-12 trunk 44563), so I should probably just wait for 2.1.1 to be released.

**Comment by mbj** [comment]
@lgierth For reference. `2.1.0` crashes also with anima.

**Comment by dkubb** [comment]
@lgierth I'm curious if you tried any work-arounds, like maybe restructuring the code to not trigger the exception? I would accept patches to change the code as long as it didn't change the functionality.

I may do some digging too, since this is causing failures on a few other projects I'm testing on 2.1.0. I'd rather have something working now than wait for 2.2.0.

**Comment by mbj** [comment]
@dkubb For you interest: I found numerous of segfaults with MRI-2.1.0, in various places of my commercial code base. I'd not use 2.1.0 in production. Seems this release wasnt that well tested. Hoping for next.

**Comment by dkubb** [comment]
@mbj I'm kinda curious if the MRI release is ever run against the rubygems corpus. It seems like it would be easy to get a list of gems that pass with a previous release (from travis or circle-ci), and then run the test suite against them. I'm guessing the travis or circle-ci would even help with such a test, especially prior to a stable release.

**Comment by mbj** [comment]
@dkubb From my discussions with implementators of jruby/rbx I remember that the MRI guys dont even use rubyspec during their build.

I'd love if MRI would listen more and cleanup ugly issues in ruby instead of adding more and more syntax.

**Comment by ghost** [comment]
@dkubb Didn't try variations of the code, since I also have a couple of other problems with 2.1.0, and thus just decided to consider it a half-broken release.
